# This is a generated file. Not intended for manual editing.
services:
  cloud-mining.api:
    build:
      context: "C:\\Users\\nrane\\Desktop\\Projects\\CloudMining\\src\\CloudMining.Api"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "cloud-mining.api:dev"
    ports:
    - "127.0.0.1:57013:57100"
    - "127.0.0.1:57213:57300"
    volumes:
    - "C:\\Users\\nrane\\AppData\\Roaming\\Microsoft\\UserSecrets:/home/app/.microsoft/usersecrets"
    - "C:\\Users\\nrane\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\nrane\\Desktop\\Projects\\CloudMining\\src\\CloudMining.Api:/app:rw"
    - "C:\\Users\\nrane\\Desktop\\Projects\\CloudMining:/src:rw"
    - "C:\\Users\\nrane\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.1.6\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.3.2\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\nrane\\AppData\\Local\\JetBrains\\Rider2024.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_10_17_16_57_47:/var/opt/rider-debugger:rw"
    working_dir: "/app"
