/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Authentication: typeof import('./src/components/Authentication.vue')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Forbidden: typeof import('./src/components/Forbidden.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Members: typeof import('./src/components/Members.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    NotificationsSettings: typeof import('./src/components/NotificationsSettings.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Password: typeof import('primevue/password')['default']
    Payments: typeof import('./src/components/Payments.vue')['default']
    Registration: typeof import('./src/components/Registration.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('primevue/tag')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
